Revert "net: Notify ConnectivityService of runtime permission changes"
This reverts commit a60ea7384278693ea3b24eb114e7ea96649b7654.

frameworks/base/services/core/java/com/android/server/net/NetworkPolicyManagerService.java:777: error: cannot find sym
bol
            mConnManager.onPackagePermissionChanged(uid);
                        ^
  symbol:   method onPackagePermissionChanged(int)
  location: variable mConnManager of type ConnectivityManager
1 error

Signed-off-by: Kazuki Hashimoto <kazukih@tuta.io>